# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'takipci.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(581, 824)
        self.btnBack = QtWidgets.QPushButton(Form)
        self.btnBack.setGeometry(QtCore.QRect(30, 770, 93, 28))
        self.btnBack.setObjectName("btnBack")
        self.btnNext = QtWidgets.QPushButton(Form)
        self.btnNext.setGeometry(QtCore.QRect(450, 770, 93, 28))
        self.btnNext.setObjectName("btnNext")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 70, 491, 671))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbusername = QtWidgets.QLabel(self.layoutWidget)
        self.lbusername.setText("")
        self.lbusername.setObjectName("lbusename")
        self.verticalLayout.addWidget(self.lbusername)
        self.lbusername_2 = QtWidgets.QLabel(self.layoutWidget)
        self.lbusername_2.setText("")
        self.lbusername_2.setObjectName("lbusername_2")
        self.verticalLayout.addWidget(self.lbusername_2)
        self.lbusername_3 = QtWidgets.QLabel(self.layoutWidget)
        self.lbusername_3.setText("")
        self.lbusername_3.setObjectName("lbusername_3")
        self.verticalLayout.addWidget(self.lbusername_3)
        self.lbusername_4 = QtWidgets.QLabel(self.layoutWidget)
        self.lbusername_4.setText("")
        self.lbusername_4.setObjectName("lbusername_4")
        self.verticalLayout.addWidget(self.lbusername_4)
        self.lbusername_5 = QtWidgets.QLabel(self.layoutWidget)
        self.lbusername_5.setText("")
        self.lbusername_5.setObjectName("lbusername_5")
        self.verticalLayout.addWidget(self.lbusername_5)
        self.lbusername_6 = QtWidgets.QLabel(self.layoutWidget)
        self.lbusername_6.setText("")
        self.lbusername_6.setObjectName("lbusername_6")
        self.verticalLayout.addWidget(self.lbusername_6)
        self.lbusername_7 = QtWidgets.QLabel(self.layoutWidget)
        self.lbusername_7.setText("")
        self.lbusername_7.setObjectName("lbusername_7")
        self.verticalLayout.addWidget(self.lbusername_7)
        self.lbusername_8 = QtWidgets.QLabel(self.layoutWidget)
        self.lbusername_8.setText("")
        self.lbusername_8.setObjectName("lbusername_8")
        self.verticalLayout.addWidget(self.lbusername_8)
        self.lbusername_9 = QtWidgets.QLabel(self.layoutWidget)
        self.lbusername_9.setText("")
        self.lbusername_9.setObjectName("lbusername_9")
        self.verticalLayout.addWidget(self.lbusername_9)
        self.lbusername_10 = QtWidgets.QLabel(self.layoutWidget)
        self.lbusername_10.setText("")
        self.lbusername_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.lbusername_10)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnBack.setText(_translate("Form", "Back"))
        self.btnNext.setText(_translate("Form", "Next"))
